export const Commentaries = [
  "This image showcases the stunning beauty of nature.",
  "The city skyline at night is a breathtaking sight to behold.",
  "A piece of abstract art that sparks the imagination.",
  "Explore the urban landscape with this captivating image.",
  "Immerse yourself in the serenity of nature's beauty.",
  "This photograph captures the essence of tranquility in nature.",
  "An exquisite display of colors and textures in this image.",
  "The architectural details in this photo are truly remarkable.",
  "A mesmerizing composition that evokes a sense of wonder.",
  "This image is a testament to the power of human creativity.",
  "A visual feast for the eyes that leaves you in awe.",
  "Discover the hidden beauty of everyday objects through this picture.",
  "The interplay of light and shadow in this image is captivating.",
  "An enchanting scene that transports you to another world.",
  "This photograph is a celebration of the diversity of life.",
  "A stunning juxtaposition of elements that creates a sense of harmony.",
  "The vibrant colors in this image evoke a feeling of joy.",
  "Explore the depth and complexity of emotions with this artwork.",
  "An awe-inspiring panorama that stretches as far as the eye can see.",
  "This image invites you to embark on a journey of exploration.",
  "A captivating snapshot frozen in time, telling a story of its own.",
  "The intricate details in this photo reveal a hidden world.",
  "Immerse yourself in the rich tapestry of nature's wonders.",
  "A thought-provoking image that challenges your perspective.",
  "This photograph captures a fleeting moment of pure beauty.",
  "The play of light and shadow in this picture is simply mesmerizing.",
  "Discover the beauty in simplicity with this minimalist composition.",
  "An evocative image that stirs the imagination and emotions.",
  "This artwork invites you to contemplate the mysteries of life.",
  "A breathtaking view that leaves you breathless with its grandeur.",
  "The tranquility captured in this image is truly calming.",
  "Embark on a visual journey through this mesmerizing photograph.",
  "An exploration of shapes and forms that captivate the eye.",
  "The symphony of colors in this image is visually striking.",
  "This picture invites you to take a moment and appreciate the beauty around you.",
  "A glimpse into a different world through the lens of this photograph.",
  "The textures in this image are so vivid, you can almost feel them.",
  "A mesmerizing play of patterns that draws you in.",
  "This artwork invites you to reflect on the mysteries of the universe.",
  "A stunning portrayal of motion frozen in time.",
  "The contrast in this photo creates a sense of drama and intrigue.",
  "Immerse yourself in the tranquility of this serene landscape.",
  "This image captures the essence of a fleeting moment.",
  "A captivating composition that leaves room for interpretation.",
  "The beauty of simplicity shines through in this photograph.",
  "An intriguing perspective that challenges your perception.",
  "This artwork is a visual poem that speaks to the soul.",
  "A moment of pure bliss captured in this image.",
  "The interplay of light and color in this picture is mesmerizing.",
  "Discover the hidden stories behind everyday scenes with this photo.",
  "An artistic exploration that pushes the boundaries of creativity.",
  "This image invites you to escape into a world of imagination.",
];
